### ISSUE TITLE
smoothget doesn't manage absolute paths

### ISSUE THREAD

**Issue by Stemby** [Milek7/smoothget#1]
Hi,
if I run `mono smoothget.exe http://[...].ism/manifest /home/USER/Downloads`, I get the video in `./home/USER/Downloads` (smoothget creates the missing directories).

My OS is Debian testing.

Best regards,
Carlo

**Comment by Milek7** [comment]
Solved. (i think ;))

**Comment by Stemby** [comment]
Thank you, @Milek7 !

1 goldstar for you. @changetip

**Comment by changetip** [comment]
Hi milek7, Stemby sent you a Bitcoin tip worth 1 goldstar (1,096 bits/$0.50), and I'm here to deliver it ➔ **[collect your tip at ChangeTip.com](https://www.changetip.com/collect/112059)**.

**[Is this real?](https://www.changetip.com/tip-online/github)**
